### ISSUE TITLE
Tests crash

### ISSUE THREAD

**Issue by yurivict** [LLNL/Aluminum#179] opened 2023-03-07 10:01 UTC
```
[yv:04179] *** Process received signal ***
[yv:04179] Signal: Segmentation fault (11)
[yv:04179] Signal code: Address not mapped (1)
[yv:04179] Failing at address: 0x440000c8
[yv:04179] [ 0] 0x8260bcb1e <pthread_sigmask+0x54e> at /lib/libthr.so.3
[yv:04179] [ 1] 0x8260bc0cf <pthread_setschedparam+0x83f> at /lib/libthr.so.3
[yv:04179] [ 2] 0x7ffffffff2d3 <_fini+0x7fffffbdb5e7> at ???
[yv:04179] [ 3] 0x822f320d8 <MPI_Comm_get_attr+0x58> at /usr/local/mpi/openmpi/lib/libmpi.so.40
[yv:04179] [ 4] 0x82165de57 <_ZN2Al8internal3mpi4initERiRPPc+0xf7> at /usr/ports/net/aluminum/work/.build/src/libAl.so.1.2.1
[yv:04179] [ 5] 0x82165ab49 <_ZN2Al10InitializeERiRPPc+0x19> at /usr/ports/net/aluminum/work/.build/src/libAl.so.1.2.1
[yv:04179] [ 6] 0x4054b0 <main+0x40> at /usr/ports/net/aluminum/work/.build/test/test_exchange
[yv:04179] *** End of error message ***
*** Signal 11
```

Version: 1.2.1
clang-14
FreeBSD 13.1

**Comment by ndryden** [comment] 2023-03-07 19:31
This appears to be a crash in MPI (specifically, a call to `MPI_Comm_get_attr` during Aluminum's initialization of MPI). I can't reproduce this on our systems, so I need more details to debug this. This is unusual enough that I suspect there may be some issue in your MPI install. Can it run `MPI_Comm_get_attr` independently of Aluminum?

**Comment by ndryden** [comment] 2023-03-18 20:35
Closing due to insufficient information. Please reopen or make a new issue if there's more information. Thanks!

**Closed by ndryden** 2023-03-18 20:35 UTC
